{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "flask-app.fullname" . }}

  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}

  metrics:

    {{- if .Values.autoscaling.cpu.enabled }}
    - type: ContainerResource
      containerResource:
        name: cpu
        container: flask
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.cpu.targetUtilizationPercentage }}
    {{- end }}

    {{- if .Values.autoscaling.memory.enabled }}
    - type: ContainerResource
      containerResource:
        name: memory
        container: flask
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.memory.targetUtilizationPercentage }}
    {{- end }}

{{- end }}